#!/usr/bin/env python3
"""Pack items.txt into worker/src/data.js for the Cloudflare Worker.

The Worker decides what is released at the moment a reader asks, so nothing
has to run on a schedule. Every item's XML and HTML is rendered here by
build.py, so the Worker and the static build stay identical.

    python3 make_worker.py
"""

import json
from pathlib import Path

import build

SITE, LAST, STATUS, ROWS = "__SITE__", "__LASTBUILD__", "__STATUS__", "__ROWS__"


def main():
    items = build.load_items()
    data = {
        "head": build.rss_head(SITE, LAST),
        "tail": build.RSS_TAIL,
        "page": build.page(SITE, STATUS, ROWS),
        "items": [
            {
                "t": int(i["replay"].timestamp() * 1000),
                "xml": build.item_xml(i),
                "html": build.item_html(i),
                "next": build.next_label(i),
            }
            for i in items
        ],
    }
    out = Path(__file__).resolve().parent / "worker" / "src" / "data.js"
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text("// Generated by make_worker.py from items.txt. Do not edit.\n"
                   f"export default {json.dumps(data, ensure_ascii=False, indent=1)};\n", encoding="utf-8")
    print(f"{out}: {len(items)} items")


if __name__ == "__main__":
    main()
